### PR TITLE
some doco and improvement on abstraction.

### PR DESCRIPTION
**Pull request by bsutton**

### CODE REVIEW

**Comment by rlsutton1** [comment]
The motor interface would be more correctly name servoConfig or ServoProperties.

In the axis enum It would also be nice to include the axis of rotation (x, y or z), and rather than comments java doc would be much nicer.

**Comment by bsutton** [comment]
actually I'm going to disagree with you on the 'servo' vs motor. Motor may not be correct but we should assume that the kinematics algorithm can be used with any 'driver' device. Motor, Servo, Stepper etc.
The kinematics algorithm should only work with angles and have no concept of how the underlying implementation achieves change of location.

As I think about it what you have as a 'Joint' should probably be renamed 'JointDefinition' and instead of Motor or Servo we should use 'Joint' which is an interface. The users implementation of Joint then knows how to actually move the joint dictated by the kinematics calculation of the desired angle.

To be consistent Link should probably be renamed 'LinkDefinition' or similar.

Thoughts?

**Comment by bsutton** [comment]
also what do you mean by:

In the axis enum It would also be nice to include the axis of rotation (x, y or z)

**Comment by bsutton** [comment]
Definitions are now immutable. Still not happy with the core structure but its better.

**Pull request merged**
